Traceback (most recent call last):
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 101, in <module>
    main()
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 89, in main
    res_temp = list(list(zip(*res_mat))[0]) # AP at threshold of 0.5
IndexError: list index out of range
Traceback (most recent call last):
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 101, in <module>
    main()
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 89, in main
    res_temp = list(list(zip(*res_mat))[0]) # AP at threshold of 0.5
IndexError: list index out of range
Traceback (most recent call last):
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 101, in <module>
    main()
  File "/home/yfong/.local/lib/python3.9/site-packages/syotil/__main__.py", line 89, in main
    res_temp = list(list(zip(*res_mat))[0]) # AP at threshold of 0.5
IndexError: list index out of range
